services:
  ingestion:
    build: .
    container_name: yellow_taxi_ingestion
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_GCS_BUCKET=${GCP_GCS_BUCKET}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS_PATH}:/app/credentials.json
